### ISSUE TITLE
Running tests without packaging results in errors (due to relative imports)

### ISSUE THREAD

**Issue by Freso** [beetbox/confuse#54]
Under Python 2, running `python2 -m nose` gives:
```
...................E................EEEE
======================================================================
ERROR: Failure: ValueError (Attempted relative import in non-package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/makepkg/python-confuse/src/python2/test/test_dump.py", line 6, in <module>
    from . import _root
ValueError: Attempted relative import in non-package

======================================================================
ERROR: Failure: ValueError (Attempted relative import in non-package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/makepkg/python-confuse/src/python2/test/test_valid.py", line 13, in <module>
    from . import _root
ValueError: Attempted relative import in non-package

======================================================================
ERROR: Failure: ValueError (Attempted relative import in non-package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/makepkg/python-confuse/src/python2/test/test_validation.py", line 12, in <module>
    from . import _root
ValueError: Attempted relative import in non-package

======================================================================
ERROR: Failure: ValueError (Attempted relative import in non-package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/makepkg/python-confuse/src/python2/test/test_views.py", line 8, in <module>
    from . import _root
ValueError: Attempted relative import in non-package

======================================================================
ERROR: Failure: ValueError (Attempted relative import in non-package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/makepkg/python-confuse/src/python2/test/test_yaml.py", line 6, in <module>
    from . import TempDir
ValueError: Attempted relative import in non-package

----------------------------------------------------------------------
Ran 40 tests in 0.073s

FAILED (errors=5)
```

Under Python 3 `python3 -m nose` gives:
```
...................E................EEEE
======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/makepkg/python-confuse/src/python3/test/test_dump.py", line 6, in <module>
    from . import _root
ImportError: attempted relative import with no known parent package

======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/makepkg/python-confuse/src/python3/test/test_valid.py", line 13, in <module>
    from . import _root
ImportError: attempted relative import with no known parent package

======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/makepkg/python-confuse/src/python3/test/test_validation.py", line 12, in <module>
    from . import _root
ImportError: attempted relative import with no known parent package

======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/makepkg/python-confuse/src/python3/test/test_views.py", line 8, in <module>
    from . import _root
ImportError: attempted relative import with no known parent package

======================================================================
ERROR: Failure: ImportError (attempted relative import with no known parent package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/makepkg/python-confuse/src/python3/test/test_yaml.py", line 6, in <module>
    from . import TempDir
ImportError: attempted relative import with no known parent package

----------------------------------------------------------------------
Ran 40 tests in 0.071s

FAILED (errors=5)
```

Running tests on the code without first installing it as a package is needed for testing during packaging, where tests are run after the build stage (ie., `python{2,3} setup.py build` has been run) but before the packaging/install stage.

**Comment by sampsyo** [comment]
Hi! This does seem like a problem, but I'm afraid I don't completely understand what's going wrong. Specifically, I don't quite see why the test runners on your system don't see `test` as a package—it's got an `__init__.py`, so this should work.

Which directory are you in (i.e., what's the cwd) when you run `python -m nose`?

To test this out, I just spun up an empty Docker container (using Alpine) and tried running Nose under both Python versions. It worked both times:

```
bash-4.4# python3 -m nose
...............................................S...............S....................................................................S...................S............................................
----------------------------------------------------------------------
Ran 197 tests in 0.323s

OK (SKIP=4)
bash-4.4# python2 -m nose
....................................................S.......................................................................SS.......................................................................
----------------------------------------------------------------------
Ran 197 tests in 0.247s

OK (SKIP=3)
```

This is when running from the `confuse` directory (a checkout of `master`).

**Comment by Freso** [comment]
The steps can be followed in [the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-confuse&id=b052d09a1d9ab3f9783b6df83044924448b629a4):

1. It downloads .tar.gz from PyPI ([#](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-confuse&id=b052d09a1d9ab3f9783b6df83044924448b629a4#n14)) and unpacks and then copies this to a "python2" and a "python3" folder ([#](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-confuse&id=b052d09a1d9ab3f9783b6df83044924448b629a4#n19)).
2. It `cd`s into those root folders and run `python{2,3} setup.py build` ([#](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-confuse&id=b052d09a1d9ab3f9783b6df83044924448b629a4#n24)).
3. It `cd`s into those root folders and run `python{2,3} -m nose` ([#](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-confuse&id=b052d09a1d9ab3f9783b6df83044924448b629a4#n34)).
4. It fails with the above errors.

Curious that it’s behaving different for you.

**Comment by arcresu** [comment]
Aha, the difference is that the package on PyPi is missing the `__init__.py`! That explains why we weren't seeing issues running from source. I think this just needs a tweak to the manifest.

**Comment by arcresu** [comment]
After fixing the manifest I built an sdist tarball and unpacked it. The tests now run fine from that directory. This will be fixed next time we make releases of these packages, but I guess if you don't want to wait for that you could consider using the GitHub releases as the source for packaging, at least temporarily.

Thanks for pointing this out, and thanks to both you and Adrian for being super explicit with the steps you were following so that the difference jumped out!

**Comment by sampsyo** [comment]
Awesome work!! That would do it—thanks for tracking this down. I wouldn't have guessed that `__init__.py` wasn't getting included by our MANIFEST.in.

We can release version 1.0.1 with this change sooner rather than later.
